//
// Generated by dtk
// Translation Unit: d_a_tag_ba1.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "d/actor/d_a_tag_ba1.h"
#include "d/d_com_inf_game.h"

class daTag_Ba1_HIO_c : public JORReflexible {
public:
    struct hio_prm_c {
        /* 0x0C */ u8 field_0x0c;
    };

    daTag_Ba1_HIO_c();
    virtual ~daTag_Ba1_HIO_c() {}

    void genMessage(JORMContext* ctx) {}

public:
    /* 0x04 */ s8 mNo;
    /* 0x08 */ s32 mCounter;
    /* 0x0C */ hio_prm_c prm;
};

static daTag_Ba1_HIO_c l_HIO;

/* 000000EC-00000144       .text __ct__15daTag_Ba1_HIO_cFv */
daTag_Ba1_HIO_c::daTag_Ba1_HIO_c() {
    static hio_prm_c a_prm_tbl = {
        0,
    };
    memcpy(&prm, &a_prm_tbl, sizeof(a_prm_tbl));
    mNo = -1;
    mCounter = -1;
}

static char* l_evn_tbl[] = {
    "Use_Fairy",
};

/* 00000144-00000164       .text daTag_Ba1_XyCheck_cB__FPvi */
static s16 daTag_Ba1_XyCheck_cB(void* i_this, int i_itemBtn) {
    return ((daTag_Ba1_c*)i_this)->XyCheck_cB(i_itemBtn);
}

/* 00000164-00000184       .text XyCheck_cB__11daTag_Ba1_cFi */
s16 daTag_Ba1_c::XyCheck_cB(int i_itemBtn) {
    return dComIfGp_getSelectItem(i_itemBtn) == dItemNo_FAIRY_BOTTLE_e;
}

/* 00000184-000001A4       .text daTag_Ba1_XyEvent_cB__FPvi */
static s16 daTag_Ba1_XyEvent_cB(void* i_this, int i_itemBtn) {
    return ((daTag_Ba1_c*)i_this)->XyEvent_cB(i_itemBtn);
}

/* 000001A4-000001C0       .text XyEvent_cB__11daTag_Ba1_cFi */
s16 daTag_Ba1_c::XyEvent_cB(int) {
    mCutIdx = 0;
    return mEventIdx[mCutIdx];
}

/* 000001C0-00000288       .text createInit__11daTag_Ba1_cFv */
bool daTag_Ba1_c::createInit() {
    bool bit = dComIfGs_isEventBit(0x520);
    if (!bit) {
        return bit;
    }

    bool not_set = dComIfGs_isEventBit(0x2A20) == 0;
    if (not_set) {
        attention_info.flags = 8;
        attention_info.distances[3] = 0x1A;
        mEventIdx[0] = dComIfGp_evmng_getEventIdx(l_evn_tbl[0], 0xFF);
        eventInfo.setXyCheckCB(daTag_Ba1_XyCheck_cB);
        eventInfo.setXyEventCB(daTag_Ba1_XyEvent_cB);
    }
    return not_set;
}

/* 00000288-00000290       .text _draw__11daTag_Ba1_cFv */
BOOL daTag_Ba1_c::_draw() {
    return TRUE;
}

/* 00000290-00000340       .text _execute__11daTag_Ba1_cFv */
BOOL daTag_Ba1_c::_execute() {
    int staffId = -1;
    if (dComIfGp_event_runCheck() && !eventInfo.checkCommandTalk()) {
        staffId = dComIfGp_evmng_getMyStaffId("TagBa1", NULL, 0);
    }
    if (staffId >= 0) {
        if (dComIfGp_evmng_endCheck(mEventIdx[mCutIdx])) {
            dComIfGp_event_onEventFlag(8);
            fopAcM_delete(this);
        }
    }
    return TRUE;
}

/* 00000340-00000394       .text _delete__11daTag_Ba1_cFv */
BOOL daTag_Ba1_c::_delete() {
    if (l_HIO.mCounter >= 0 && --l_HIO.mCounter < 0) {
        mDoHIO_deleteChild(l_HIO.mNo);
    }
    return TRUE;
}

/* 00000394-00000454       .text _create__11daTag_Ba1_cFv */
cPhs_State daTag_Ba1_c::_create() {
    if (l_HIO.mCounter < 0) {
        l_HIO.mNo = mDoHIO_createChild("おばあちゃんタグ", &l_HIO);
    }
    l_HIO.mCounter++;

    fopAcM_ct(this, daTag_Ba1_c);

    if (!createInit()) {
        return cPhs_ERROR_e;
    }
    return cPhs_COMPLEATE_e;
}

/* 00000454-00000474       .text daTag_Ba1_Create__FP10fopAc_ac_c */
static cPhs_State daTag_Ba1_Create(fopAc_ac_c* i_this) {
    return ((daTag_Ba1_c*)i_this)->_create();
}

/* 00000474-00000494       .text daTag_Ba1_Delete__FP11daTag_Ba1_c */
static BOOL daTag_Ba1_Delete(daTag_Ba1_c* i_this) {
    return ((daTag_Ba1_c*)i_this)->_delete();
}

/* 00000494-000004B4       .text daTag_Ba1_Execute__FP11daTag_Ba1_c */
static BOOL daTag_Ba1_Execute(daTag_Ba1_c* i_this) {
    return ((daTag_Ba1_c*)i_this)->_execute();
}

/* 000004B4-000004D4       .text daTag_Ba1_Draw__FP11daTag_Ba1_c */
static BOOL daTag_Ba1_Draw(daTag_Ba1_c* i_this) {
    return ((daTag_Ba1_c*)i_this)->_draw();
}

/* 000004D4-000004DC       .text daTag_Ba1_IsDelete__FP11daTag_Ba1_c */
static BOOL daTag_Ba1_IsDelete(daTag_Ba1_c*) {
    return TRUE;
}

static actor_method_class l_daTag_Ba1_Method = {
    (process_method_func)daTag_Ba1_Create,
    (process_method_func)daTag_Ba1_Delete,
    (process_method_func)daTag_Ba1_Execute,
    (process_method_func)daTag_Ba1_IsDelete,
    (process_method_func)daTag_Ba1_Draw,
};

actor_process_profile_definition g_profile_TAG_BA1 = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0007,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_TAG_BA1_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daTag_Ba1_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_TAG_BA1_e,
    /* Actor SubMtd */ &l_daTag_Ba1_Method,
    /* Status       */ fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_0_e,
};
